language: node_js
node_js:
  - stable
install:
  - npm install
cache:
  directories:
    - node_modules

env:
  global:
    # SAUCE_USERNAME
    - secure: ifatBVQy/xXw+njlVMi085KWxPDjTFs8+Jc/DFOSkhrMI03dEjLwh1Flwnkbd0AkNhmFKyR78ovAKphjRC3orY63pASIkIisPce+YxSHsGGt0t/JSO1ltnedkRr/rA/D/Qnrv7cv/Xwv1U6sI08HII8P9092zMOEFMPTV59EIPrrdvC8wpFM0MtsO7HQbZy8saYP8KlaifLF//4cRv4+fTSXzC23gfjBQyYPcRu/rJVXeuuf1nW25Ehu1+T4hXZ71NqXCzczF6hYGSrUFaebuR9G/SmZAG9f3appD+Vr1IcFlnGJWFODGWr6aXnAAsL1Bb7mX3hPwXEOWISuQNu+UdnpIGdz6CbovhIUd4kzPdUhC3w917z7THGWbkD6QpZWc6Beo9VzSc3eJQ4dFxzyTSsTr69qhPw9/88Vv/BqWPnz8MRf195LwHGIiWnxYIhWMhj9VUD4IZbZFPWyHVZnR+ooniU42RsSbgShdhPAzMwu2ZIkKg4r4bohyT8zX5VUrR7P1nCFqDp3eXl6IGmhWPV5QEsEOmrVz4K48fxIQZAFYg1yMH0P9yhQIkfsjRaGaQ2NK0OcPTkbqy15FIFK74anR4c4ZuruU0SrzdRtFt5bAO7FFkTfF+wvYbPQgtGDu2LZUqKMD4UsfGHnqO668rgIwGSv9I8DkU08ysH+aeo=
    # SAUCE_ACCESS_KEY
    - secure: qBv6RA3NphnOjBajL3c3bMn+FB34Nf/E8sNmDmyY6aPZR1VS8Yt8xbrkccAvwgEf5Mq7lf2O+AVyBTUSdWbzzuFcQmi9p27Tl9jjiUTGRG4NhTatCQzLRklZro6n75Op6Z0cxKBmDMit8lzTYFdeIVz0LLTZYSP4WGpSVSaJEPa7X81AKfKIZXRaDhAQoBadxUfJYO6KhS+pr7Fi0FSGX8L0/oo/B5max6YSANGO8mIpP6td1+tmRRidNYv2xtUy19P881DCTYAdmELK6xTLuC6Hx+LdYLnZ8ooihCRNW2fX3zB5JT4jciuPoqNPu5Fp6nKXoVpFXDjSOQ0Km50iM+uQF7qN8ZdsMuGU99oAzM0SBx/iCKajW3x2MBXTHzjC8RGW9il0pDUVJ+XKzAYnyJGGYRgXDT9MR96e67cPqqkFqX73e1K+iwFt1rAl8Qbh/GYEWSDrJfcSLe1SOWpOOeh50T/3fikvhmgzz8Nm8pFhTDZBYo41OViG9qVLlsB9hd5NePdFrXd3o6b8D8oJyfZySfhgY4lBVCxn/h9ZggDxQaiCQVN+qFuAYtfUtdERh4SlzMpFTxPlg3PQ+Qk98eFzRtAyN4o9ilwjRwt1tksfFZzP6SirHA+iZT/0jNAOiaLZvtCrpgHxD38uhtPrTvZU6u6/5+L9BUW4YVhmFfM=

script:
  - npm run test:sauce
